### ISSUE TITLE
Error in preprocessing

### ISSUE THREAD

**Issue by smanne07** [cole-trapnell-lab/cicero-release#25]
Hi Hannah,
I have succesfully the cicero pipeline on 10x generated data but for only one of the samples i have the following error:

`Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed
Calls: [<- -> [<- -> [<- -> [<- -> int2i
In addition: Warning message:
In int2i(as.integer(i), n) : NAs introduced by coercion to integer range`

Does this error point to anything with how the data is for this sample?I tried to check from where this error is raised and i could see that this part of the preprocess/reduceDimension functions,but i cannot figure out why

Can you help in troubleshooting this?

Thank you
Sasi

**Comment by hpliner** [comment]
There've been a couple of reports of this problem but I haven't been able to reproduce it with the publicly available 10x datasets. A couple of questions: is this human data? Is there any possibility of NAs, Infs or NaNs in your expression matrix?

**Comment by smanne07** [comment]
This is mouse data,i will check if and how the NAs were introduced in this dataset

**Comment by hpliner** [comment]
Ok, let me know if possible. Also happy to debug myself if you can share the data

**Comment by smanne07** [comment]
Hi Hannah,
Looking in to the data it looks it is an issue similar to https://github.com/sdparekh/zUMIs/issues/105

This is happenning when we have data from larger number of cells(In my case 14000 failed against 10000 which was succesfull)

https://bitbucket.org/hrue/r-inla/issues/1/logical-indexing-for-large-matrices-fails

Thank you
Sasi

**Comment by smanne07** [comment]
traceback()
7: int2i(as.integer(i), n)
6: `[<-`(x, i, value = value)
5: `[<-`(x, i, value = value)
4: `[<-`(`*tmp*`, ncounts != 0, value = 1)
3: `[<-`(`*tmp*`, ncounts != 0, value = 1)
2: normalize_expr_data(cds, norm_method, pseudo_expr)
1: reduceDimension(input_cds, max_components = 2, num_dim = 6, reduction_method = "tSNE", 
       norm_method = "none")


normalize_expr_data for binomialff family

FM <- exprs(input_cds)
 ncounts <- FM > 0
 **ncounts[ncounts != 0] <- 1**

Is causing issues with larger matrices.

**Comment by hpliner** [comment]
Thanks for the traceback and info. I just pushed a fix to monocle3, so if you rerun the installation described here: http://cole-trapnell-lab.github.io/monocle-release/monocle3/ It should work now!

**Comment by smanne07** [comment]
hi @hpliner ,
I was trying Cicero with the latest monocle3 installed and i am still facing the same issue with the error 

`Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed Calls: [<- -> [<- -> [<- -> [<- -> int2i In addition: Warning message: In int2i(as.integer(i), n) : NAs introduced by coercion to integer range`

What is the current recommendation for running Cicero on large datasets?Which monocle version?

Thank you
Sasi

**Comment by huidongchen** [comment]
Hi 

Thanks for creating this amazing tool. Unfortunately i'm also having the same issue. 

```
Warning message in int2i(as.integer(i), n):
"NAs introduced by coercion to integer range"
Error in if (any(i < 0L)) {: missing value where TRUE/FALSE needed
Traceback:

1. reduceDimension(input_cds, max_components = 2, num_dim = 15, 
 .     reduction_method = "tSNE", norm_method = "none")
2. normalize_expr_data(cds, norm_method, pseudo_expr)
3. `[<-`(`*tmp*`, ncounts != 0, value = 1)
4. `[<-`(`*tmp*`, ncounts != 0, value = 1)
5. as(.TM.repl.i.mat(as(x, "TsparseMatrix"), i = i, value = value), 
 .     "CsparseMatrix")
6. .class1(object)
7. .TM.repl.i.mat(as(x, "TsparseMatrix"), i = i, value = value)
8. `[<-`(x, i, value = value)
9. `[<-`(x, i, value = value)
10. int2i(as.integer(i), n)
```

In my case I have ~12,000 cells

**Comment by hpliner** [comment]
Cicero should now be up to date with the new Monocle3 beta (https://cole-trapnell-lab.github.io/monocle3/) on it's monocle3 branch. Can you check out the latest instructions here https://cole-trapnell-lab.github.io/cicero-release/docs_m3/ and let me know if that solves your issue?
